=== UFC-MDCC-HPC/HPC-Storm-SAFe/safe-client-application/src/br/ufc/mdcc/pargo/safe/xml/montage-component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/montage-component" xmlns:tns="http://www.example.org/montage-component" elementFormDefault="qualified">

    <element name="library" type="tns:MontageLibrary"></element>
    
    <complexType name="MontageLibrary">
    	<sequence>
    		<element name="mComponent" type="tns:MontageComponent"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="MontageComponent">
    	<sequence>
    		<element name="inParam" type="tns:InParam" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="outParam" type="tns:outParam" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="InParam">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="type" type="tns:enumType"></attribute>
    </complexType>

    <complexType name="outParam">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="type" type="tns:enumType"></attribute>
    </complexType>

    <simpleType name="enumType">
    	<restriction base="string">
    		<enumeration value="FILE_TYPE"/>
    		<enumeration value="DIR_TYPE"/>
    		<enumeration value="PARAM_TYPE"/>
    	</restriction>
    </simpleType>
</schema>

=== UFC-MDCC-HPC/HPC-Storm-SAFe/safe-client-application/src/montage-components.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:library xmlns:tns="http://www.example.org/montage-component"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/montage-component br/ufc/mdcc/pargo/safe/xml/montage-component.xsd ">

	<tns:mComponent name="mImgtbl">
		<tns:inParam name="img_dir" type="DIR_TYPE" />
		<!-- <tns:inParam name="out_name" type="PARAM_TYPE" /> -->
		<tns:outParam name="tbl_file" type="FILE_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mAdd">
		<tns:inParam name="config_param" type="PARAM_TYPE" />
		<!--<tns:inParam name="out_name" type="PARAM_TYPE" /> -->
		<tns:inParam name="img_dir" type="DIR_TYPE" />
		<tns:inParam name="tbl_file" type="FILE_TYPE" />
		<tns:inParam name="hdr_file" type="FILE_TYPE" />
		<tns:outParam name="fits_file" type="FILE_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mProjExec">
		<tns:inParam name="config_param" type="PARAM_TYPE" />
		<!--<tns:inParam name="out_name" type="PARAM_TYPE" /> -->
		<tns:inParam name="img_dir_1" type="DIR_TYPE" />
		<tns:inParam name="img_dir_2" type="DIR_TYPE" />
		<tns:inParam name="tbl_file" type="FILE_TYPE" />
		<tns:inParam name="hdr_file" type="FILE_TYPE" />
		<tns:outParam name="tbl_file" type="FILE_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mOverlaps">
		<tns:inParam name="tbl_file" type="FILE_TYPE" />
		<!--<tns:inParam name="out_name" type="PARAM_TYPE"/> -->
		<tns:outParam name="diff_tbl" type="FILE_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mDiffExec">
		<tns:inParam name="config_param" type="PARAM_TYPE" />
		<tns:inParam name="proj_dir" type="DIR_TYPE" />
		<tns:inParam name="diff_tbl" type="FILE_TYPE" />
		<tns:inParam name="hdr_file" type="FILE_TYPE" />
		<tns:outParam name="diff_dir" type="DIR_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mFitExec">
		<tns:inParam name="diff_tbl" type="FILE_TYPE" />
		<tns:inParam name="diff_dir" type="DIR_TYPE" />
		<tns:outParam name="tbl_file" type="FILE_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mBgModel">
		<tns:inParam name="img_tbl" type="FILE_TYPE" />
		<tns:inParam name="fit_tbl" type="FILE_TYPE" />
		<tns:outParam name="tbl_file" type="FILE_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mBgExec">
		<tns:inParam name="config_param" type="PARAM_TYPE" />
		<tns:inParam name="imgtbl_file" type="FILE_TYPE" />
		<tns:inParam name="corr_tbl" type="FILE_TYPE" />
		<tns:inParam name="proj_dir" type="DIR_TYPE" />
		<tns:outParam name="corr_dir" type="DIR_TYPE" />
	</tns:mComponent>

	<tns:mComponent name="mJpeg">
		<tns:inParam name="config_1" type="PARAM_TYPE" />
		<tns:inParam name="config_2" type="PARAM_TYPE" />
		<tns:inParam name="config_3" type="PARAM_TYPE" />
		<tns:outParam name="jpeg_file" type="FILE_TYPE" />
	</tns:mComponent>
</tns:library>
