=== UFC-MDCC-HPC/HPC-Storm-SAFe/safe-hpc/src/br/ufc/mdcc/pargo/safe/grammar/xml/SAFe_architecture_V2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	 	targetNamespace="http://www.example.org/SAFe_architecture_V2"
	 	xmlns:tns="http://www.example.org/SAFe_architecture_V2"
	    elementFormDefault="qualified">


    <complexType name="Architecture">
    	<sequence>
    		<element name="application" type="tns:Application"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="workflow" type="tns:Workflow" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="body" type="tns:kindSetType" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="env_attachment" type="tns:attachmentType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    		<element name="tsk_attachment" maxOccurs="unbounded"
    			minOccurs="1">
    			<complexType>
    				<sequence>
    					<element name="task_A" type="tns:Port"></element>
    					<element name="task_B" type="tns:Port"></element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>
    
    <element name="architecture" type="tns:Architecture"></element>

    <complexType name="Workflow">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Computation">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Repository">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Connector">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="Platform">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
    

    <complexType name="Qualifier">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="PortUses">
    	<complexContent>
    		<extension base="tns:Port"></extension>
    	</complexContent>
    </complexType>

    <complexType name="PortProvides">
    	<complexContent>
    		<extension base="tns:Port"></extension>
    	</complexContent>
    </complexType>


    <complexType name="bodyType">
    	<sequence>
    		<element name="component" type="tns:kindSetType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    
    <complexType name="Port">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="id" type="int" use="required"></attribute>
    </complexType>

    <complexType name="attachmentType">
    	<sequence>
    		<element name="uses" type="tns:PortUses" maxOccurs="1" minOccurs="1"></element>
    		<element name="provides" type="tns:PortProvides" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="Component">
    	<choice maxOccurs="unbounded" minOccurs="1">
    		<element name="env_ports" maxOccurs="1" minOccurs="0">
    			<complexType>
    				<choice maxOccurs="unbounded" minOccurs="1">
    					<element name="uses" type="tns:PortUses" maxOccurs="unbounded" minOccurs="0"></element>
    					<element name="provides" type="tns:PortProvides" maxOccurs="unbounded" minOccurs="0"></element>
    				</choice>
    			</complexType>
    		</element>
    		<element name="task_ports" maxOccurs="1" minOccurs="0">
    			<complexType>
    				<sequence>
    					<element name="task_port" type="tns:Port" maxOccurs="unbounded" minOccurs="1"></element>
    				</sequence>
    			</complexType>
    		</element>
    	</choice>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="id" type="int" use="required"></attribute>
    </complexType>


    <complexType name="kindSetType">
    	<choice maxOccurs="unbounded" minOccurs="1">
    		<element name="computation" type="tns:Computation" maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="repository" type="tns:Repository" maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="qualifier" type="tns:Qualifier" maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="platform" type="tns:Platform" maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="connector" type="tns:Connector" maxOccurs="unbounded" minOccurs="0"></element>
        </choice>
    </complexType>
    

    <complexType name="Application">
    	<complexContent>
    		<extension base="tns:Component"></extension>
    	</complexContent>
    </complexType>
</schema>

=== UFC-MDCC-HPC/HPC-Storm-SAFe/safe-hpc/src/br/ufc/mdcc/pargo/safe/grammar/arch_03_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:architecture xmlns:tns="http://www.example.org/SAFe_architecture_V2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SAFe_architecture_V2 SAFe_architecture_V2.xsd ">
  <tns:application id="0">
  	<tns:env_ports>
  		<tns:provides name="app_env_port_a" id="01"/>
  		<tns:provides name="app_env_port_b" id="02"/>
  		<tns:uses name="app_uses_port_a" id="03"/>
  	</tns:env_ports> 
  </tns:application>
  	
  <tns:workflow id="1">
  	<tns:env_ports>
  		<tns:provides name="wf_uses_port_a" id="11"/>
  		<tns:provides name="wf_uses_port_b" id="12"/>
  		<tns:uses name="wf_uses_port_a" id="13"/>
  	</tns:env_ports> 
  </tns:workflow>
  
  <tns:body>
  	
  	<tns:computation name="comp_20" id="20">
  		<tns:env_ports>	
  			<tns:provides name="cmp_uses_port_a" id="21"/>
  			<tns:provides name="cmp_uses_port_b" id="22"/>
  			<tns:uses name="cmp_uses_port_a" id="23"/>
  		</tns:env_ports>
  		<tns:task_ports>
  			<tns:task_port name="task_a" id="24"/>
  			<tns:task_port name="task_b" id="25"/>
  		</tns:task_ports>
  	</tns:computation>
  	
  	<tns:connector name="comp_30" id="30">
  		<tns:env_ports>	
  			<tns:provides name="cmp_uses_port_a" id="31"/>
  			<tns:provides name="cmp_uses_port_b" id="32"/>
  			<tns:uses name="cmp_uses_port_a" id="33"/>
  		</tns:env_ports>
  		<tns:task_ports>
  			<tns:task_port name="task_a" id="34"/>
  			<tns:task_port name="task_b" id="35"/>
  		</tns:task_ports>
  	</tns:connector>
  	
  	<tns:platform name="comp_40" id="40">
  		<tns:env_ports>	
  			<tns:provides name="cmp_uses_port_a" id="40"/>
  			<tns:provides name="cmp_uses_port_b" id="41"/>
  			<tns:uses name="cmp_uses_port_a" id="42"/>
  		</tns:env_ports>
  		<tns:task_ports>
  			<tns:task_port name="task_a" id="43"/>
  			<tns:task_port name="task_b" id="44"/>
  		</tns:task_ports>
  	</tns:platform>
  	
  	<tns:repository name="comp_50" id="50">
  		<tns:env_ports>	
  			<tns:provides name="cmp_uses_port_a" id="51"/>
  			<tns:provides name="cmp_uses_port_b" id="52"/>
  			<tns:uses name="cmp_uses_port_a" id="53"/>
  		</tns:env_ports>
  		<tns:task_ports>
  			<tns:task_port name="task_a" id="54"/>
  			<tns:task_port name="task_b" id="55"/>
  		</tns:task_ports>
  	</tns:repository>
  	
  </tns:body>
  
  <tns:attachment>
    <tns:uses name="app_uses_port_a" id="03"/>
    <tns:provides name="cmp_uses_port_b" id="41"/>
  </tns:attachment>
  
  <tns:attachment>
    <tns:uses name="cmp_uses_port_a" id="33"/>
    <tns:provides name="cmp_uses_port_b" id="22"/>
  </tns:attachment>
  
 
</tns:architecture>
